server:
  port: 18081
spring:
  application:
    name: goods
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.50.4:3306/qingcheng_goods?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: a12345678
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
    filter-only-up-instances: true
feign:
  hystrix:
    enable: true
